[package]
name = "ard"
version = "0.1.0"
authors = ["Michael Zoech <michi.zoech@gmail.com>"]

[dependencies]
cairo-rs = { version = "0.3", features = ["png"] }
gdk = "0.7"
glib = "0.4.1"
integer-atomics = "*"
num_cpus = "1.0"
rand = "0.3"

[dependencies.gtk]
version = "0.3"
features = ["v3_20"]